"use client";

import { use, useState, useEffect, useMemo, useCallback } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, RefreshCw, AlertTriangle, ExternalLink } from "lucide-react";
import CanvasShell from "@/components/canvas/CanvasShell";
import ArtifactRenderer, { type ArtifactData } from "@/components/canvas/ArtifactRenderer";
import PhaseTimeline, { type PhaseData } from "@/components/canvas/PhaseTimeline";
import { useSSE } from "@/components/canvas/useSSE";

// ── Types ──────────────────────────────────────────────────────────

interface MvpStatus {
  slug: string;
  title?: string;
  plan?: {
    title?: string;
    description?: string;
    tech_stack?: Record<string, string>;
    files?: { path: string; purpose: string }[];
    eta?: string;
  };
  status?: string;
  phase?: string;
  previewUrl?: string;
  deployedUrl?: string;
  productionUrl?: string;
  error?: string;
  created_at?: string;
  last_updated?: string;
}

interface CodeFileFromStream {
  path: string;
  content: string;
  language?: string;
  purpose?: string;
}

interface PhaseState {
  planning: "idle" | "active" | "complete" | "error";
  generating: "idle" | "active" | "complete" | "error";
  previewing: "idle" | "active" | "complete" | "error";
  deploying: "idle" | "active" | "complete" | "error";
  verifying: "idle" | "active" | "complete" | "error";
}

type CanvasShellStatus = "planning" | "generating" | "previewing" | "deploying" | "verifying" | "complete" | "error";

// ── Helpers ────────────────────────────────────────────────────────

function deriveArtifact(status: MvpStatus | null, streamedFiles: CodeFileFromStream[]): ArtifactData | null {
  if (!status) return null;

  const plan = status.plan;
  const isLive = status.productionUrl || status.deployedUrl || status.previewUrl;

  // Mini-app: preview or deployed URL available
  if (isLive) {
    return {
      type: "mini-app",
      src: status.productionUrl || status.deployedUrl || status.previewUrl || "",
      title: plan?.title || status.title || status.slug,
    };
  }

  // Code: files from plan or streamed
  const planFiles = plan?.files?.map((f) => ({
    path: f.path,
    content: `// ${f.purpose || "No description"}\n// Generated by Jarvis MVP Builder\n`,
    language: f.path.endsWith(".tsx") || f.path.endsWith(".ts")
      ? "typescript"
      : f.path.endsWith(".json")
        ? "json"
        : f.path.endsWith(".css")
          ? "css"
          : f.path.endsWith(".md")
            ? "markdown"
            : "plaintext",
  }));

  if (streamedFiles.length > 0) {
    return {
      type: "code",
      files: streamedFiles,
    };
  }

  if (planFiles && planFiles.length > 0) {
    return {
      type: "code",
      files: planFiles,
    };
  }

  // Report: plan details as markdown
  const md = [
    `# ${plan?.title || status.title || status.slug}`,
    plan?.description ? `\n${plan.description}\n` : "",
    plan?.tech_stack ? `\n## Tech Stack\n\n${Object.entries(plan.tech_stack).map(([k, v]) => `- **${k}**: ${v}`).join("\n")}\n` : "",
    plan?.eta ? `\n> Estimated time: ${plan.eta}\n` : "",
    status.error ? `\n## Error\n\n\`\`\`\n${status.error}\n\`\`\`\n` : "",
  ].filter(Boolean).join("\n");

  return { type: "report", content: md || `# ${status.slug}\n\nAwaiting data…` };
}

// ── Page ───────────────────────────────────────────────────────────

export default function SandboxPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const router = useRouter();

  const [status, setStatus] = useState<MvpStatus | null>(null);
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [connected, setConnected] = useState(false);
  const [streamedFiles, setStreamedFiles] = useState<CodeFileFromStream[]>([]);
  const [phases, setPhases] = useState<PhaseState>({
    planning: "idle",
    generating: "idle",
    previewing: "idle",
    deploying: "idle",
    verifying: "idle",
  });
  const [thinkingText, setThinkingText] = useState("");

  // ── Fetch initial status ─────────────────────────────────────
  useEffect(() => {
    let cancelled = false;
    async function fetchStatus() {
      try {
        const res = await fetch(`/api/mvp/${encodeURIComponent(slug)}`, {
          signal: AbortSignal.timeout(10000),
        });
        if (!res.ok) {
          if (res.status === 404) {
            if (!cancelled) { setFetchError("MVP_NOT_FOUND"); setLoading(false); }
          } else {
            if (!cancelled) { setFetchError(`VPS returned ${res.status}`); setLoading(false); }
          }
          return;
        }
        const data = await res.json();
        if (!cancelled) {
          setStatus(data);
          setLoading(false);
          if (data.status) updatePhasesFromStatus(data.status);
        }
      } catch (err: unknown) {
        if (!cancelled) {
          const msg = err instanceof Error ? err.message : "Failed to fetch MVP status";
          if (msg.includes("timeout")) setFetchError("VPS_UNREACHABLE");
          else setFetchError(msg);
          setLoading(false);
        }
      }
    }
    fetchStatus();
    return () => { cancelled = true; };
  }, [slug]);

  // ── Phase helpers ───────────────────────────────────────────

  const updatePhasesFromStatus = useCallback((st: string) => {
    setPhases((prev) => {
      const next = { ...prev };
      if (st === "planned" || st === "planning") next.planning = "complete";
      if (st === "generating") { next.planning = "complete"; next.generating = "active"; }
      if (st === "generated") { next.planning = "complete"; next.generating = "complete"; }
      if (st === "previewing") { next.planning = "complete"; next.generating = "complete"; next.previewing = "active"; }
      if (st === "preview_ready" || st === "deploying") {
        next.planning = "complete"; next.generating = "complete"; next.previewing = "complete"; next.deploying = "active";
      }
      if (st === "deployed" || st === "verified") {
        next.planning = "complete"; next.generating = "complete"; next.previewing = "complete";
        next.deploying = "complete"; next.verifying = "complete";
      }
      return next;
    });
  }, []);

  // ── SSE stream via useSSE hook ──────────────────────────────

  const handleSSEEvent = useCallback((eventName: string, data: unknown) => {
    const d = data as Record<string, unknown>;

    switch (eventName) {
      case "artifact_start":
        if (d.title) setStatus((prev) => prev ? { ...prev, title: String(d.title) } : prev);
        break;

      case "phase_start":
        if (d.phase) {
          const p = String(d.phase);
          setPhases((prev) => ({ ...prev, [p]: "active" as const }));
        }
        break;

      case "phase_progress":
        // Update phase step info
        break;

      case "file_start":
        if (d.path) {
          setStreamedFiles((prev) => {
            const existing = prev.find((f) => f.path === d.path);
            if (existing) return prev;
            return [...prev, {
              path: String(d.path),
              content: "",
              language: d.language ? String(d.language) : undefined,
              purpose: d.purpose ? String(d.purpose) : undefined,
            }];
          });
        }
        break;

      case "file_chunk":
        if (d.path && d.content_delta) {
          setStreamedFiles((prev) =>
            prev.map((f) =>
              f.path === d.path
                ? { ...f, content: f.content + String(d.content_delta) }
                : f,
            ),
          );
        }
        break;

      case "file_complete":
        if (d.path) {
          setStreamedFiles((prev) =>
            prev.map((f) =>
              f.path === d.path
                ? { ...f, content: (d.content as string) || f.content }
                : f,
            ),
          );
        }
        break;

      case "thinking":
        if (d.text) setThinkingText((prev) => prev + String(d.text));
        break;

      case "phase_complete":
        if (d.phase) {
          const p = String(d.phase);
          setPhases((prev) => ({ ...prev, [p]: "complete" as const }));
        }
        break;

      case "artifact_complete":
        if (d.slug) {
          setStatus((prev) => prev ? {
            ...prev,
            status: "verified",
            ...(d.deployed_url ? { productionUrl: String(d.deployed_url) } : {}),
            ...(d.preview_url ? { previewUrl: String(d.preview_url) } : {}),
          } : prev);
          updatePhasesFromStatus("verified");
        }
        break;

      case "artifact_error":
        if (d.error) setFetchError(String(d.error));
        break;

      case "mvp_status":
      case "status":
        setStatus((prev) => prev ? { ...prev, ...d as Record<string, unknown> } as MvpStatus : d as unknown as MvpStatus);
        if (d.status) updatePhasesFromStatus(String(d.status));
        if (d.phase) updatePhasesFromStatus(String(d.phase));
        break;

      case "mvp_complete":
        if (d.url) {
          setStatus((prev) => prev ? { ...prev, productionUrl: String(d.url), status: "verified" } : prev);
        }
        updatePhasesFromStatus("verified");
        break;

      case "mvp_error":
        if (d.error) setFetchError(String(d.error));
        break;

      case "phase_update":
        if (d.phase) {
          const phase = String(d.phase);
          const phaseStatus = String(d.status || "complete");
          setPhases((prev) => ({
            ...prev,
            [phase]: phaseStatus === "active" || phaseStatus === "running" ? "active"
              : phaseStatus === "error" ? "error"
              : "complete",
          }));
        }
        break;

      case "keepalive":
      case "heartbeat":
        break;

      case "system":
        // Connection established
        setConnected(true);
        break;

      default:
        // Generic update
        if (d.slug === slug || !d.slug) {
          setStatus((prev) => prev ? { ...prev, ...d as Record<string, unknown> } as MvpStatus : prev);
          if (d.status) updatePhasesFromStatus(String(d.status));
        }
    }
  }, [slug, updatePhasesFromStatus]);

  const { connected: sseConnected, error: sseError, cancel } = useSSE(
    loading ? null : `/api/mvp/${encodeURIComponent(slug)}/stream`,
    {
      onEvent: handleSSEEvent,
      onConnect: () => setConnected(true),
      onDisconnect: () => setConnected(false),
      onError: () => setConnected(false),
    },
  );

  // Sync SSE error to fetchError
  useEffect(() => {
    if (sseError && !fetchError) setFetchError(sseError);
  }, [sseError, fetchError]);

  // ── Derived state ──────────────────────────────────────────

  const artifact = useMemo(
    () => deriveArtifact(status, streamedFiles),
    [status, streamedFiles],
  );

  const timelinePhases: PhaseData[] = useMemo(() => [
    { id: "planning", label: "Planning", status: phases.planning },
    { id: "generating", label: "Generating", status: phases.generating },
    { id: "previewing", label: "Previewing", status: phases.previewing },
    { id: "deploying", label: "Deploying", status: phases.deploying },
    { id: "verifying", label: "Verifying", status: phases.verifying },
  ], [phases]);

  const title = status?.plan?.title || status?.title || status?.slug || slug;
  const canvasStatus: CanvasShellStatus =
    status?.status === "verified" || status?.productionUrl
      ? "complete"
      : status?.status?.includes("error")
        ? "error"
        : (connected || sseConnected) ? "generating" : "planning";

  const isLive = !!(status?.productionUrl || status?.deployedUrl);

  // ── Loading ─────────────────────────────────────────────────

  if (loading) {
    return (
      <CanvasShell slug={slug} title="Loading…" status="planning">
        <div className="flex flex-col items-center justify-center gap-6 py-24">
          <div className="flex items-center gap-3">
            <div className="size-6 rounded-xl bg-emerald-400/20 animate-pulse" />
            <span className="text-sm text-zinc-500 font-mono">Loading {slug}…</span>
          </div>
          <div className="grid grid-cols-5 gap-3 w-64">
            {Array.from({ length: 5 }).map((_, i) => (
              <div
                key={i}
                className="h-1.5 rounded-full bg-white/[0.04] animate-pulse"
                style={{ animationDelay: `${i * 150}ms` }}
              />
            ))}
          </div>
        </div>
      </CanvasShell>
    );
  }

  // ── Not found ───────────────────────────────────────────────

  if (fetchError === "MVP_NOT_FOUND") {
    return (
      <CanvasShell slug={slug} title="Not Found" status="error">
        <div className="flex flex-col items-center justify-center gap-6 py-24">
          <div className="flex size-16 items-center justify-center rounded-2xl bg-amber-400/10 ring-1 ring-amber-400/20">
            <AlertTriangle className="size-8 text-amber-400" />
          </div>
          <div className="text-center">
            <h1 className="text-xl font-semibold text-zinc-100 mb-1">MVP Not Found</h1>
            <p className="text-sm text-zinc-500">
              <code className="text-xs bg-white/[0.04] px-2 py-0.5 rounded">{slug}</code>
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => router.push("/chat")}
              className="inline-flex items-center gap-2 rounded-xl bg-white/[0.06] px-4 py-2 text-sm text-zinc-300 hover:bg-white/[0.1] transition-colors"
            >
              <ArrowLeft className="size-4" />
              Back to Chat
            </button>
            <button
              onClick={() => window.location.reload()}
              className="inline-flex items-center gap-2 rounded-xl bg-emerald-400/10 px-4 py-2 text-sm text-emerald-300 ring-1 ring-emerald-400/20 hover:bg-emerald-400/20 transition-colors"
            >
              <RefreshCw className="size-4" />
              Retry
            </button>
          </div>
        </div>
      </CanvasShell>
    );
  }

  // ── Error ───────────────────────────────────────────────────

  if (fetchError && fetchError !== "MVP_NOT_FOUND") {
    return (
      <CanvasShell slug={slug} title="Error" status="error">
        <div className="flex flex-col items-center justify-center gap-6 py-24">
          <div className="flex size-16 items-center justify-center rounded-2xl bg-red-400/10 ring-1 ring-red-400/20">
            <AlertTriangle className="size-8 text-red-400" />
          </div>
          <div className="text-center">
            <h1 className="text-xl font-semibold text-zinc-100 mb-1">Connection Error</h1>
            <p className="text-sm text-zinc-500">{fetchError}</p>
          </div>
          <button
            onClick={() => window.location.reload()}
            className="inline-flex items-center gap-2 rounded-xl bg-emerald-400/10 px-4 py-2 text-sm text-emerald-300 ring-1 ring-emerald-400/20 hover:bg-emerald-400/20 transition-colors"
          >
            <RefreshCw className="size-4" />
            Retry
          </button>
        </div>
      </CanvasShell>
    );
  }

  // ── Main sandbox view ───────────────────────────────────────

  return (
    <CanvasShell
      slug={slug}
      title={title}
      status={canvasStatus}
      deployedUrl={isLive ? (status?.productionUrl || status?.deployedUrl) : undefined}
      rightRail={<PhaseTimeline phases={timelinePhases} />}
      reasoningText={thinkingText}
      downloadFiles={streamedFiles.length > 0 ? streamedFiles.map((f) => ({ path: f.path, content: f.content })) : undefined}
    >
      {artifact ? (
        <ArtifactRenderer artifact={artifact} />
      ) : (
        <div className="flex flex-col items-center justify-center gap-4 py-24">
          <div className="flex size-12 items-center justify-center rounded-2xl bg-white/[0.02] ring-1 ring-white/[0.04]">
            <RefreshCw className="size-5 text-zinc-600 animate-spin" />
          </div>
          <p className="text-sm text-zinc-500">Waiting for artifact data…</p>
          {(connected || sseConnected) && (
            <span className="inline-flex items-center gap-1.5 text-xs text-emerald-400">
              <span className="size-1.5 rounded-full bg-emerald-400 animate-pulse" />
              Connected — streaming
            </span>
          )}
        </div>
      )}
    </CanvasShell>
  );
}
