// ─── Curated Marketplace Catalog ────────────────────────────────────────
// Phase 11.1 — Pre-loaded marketplace entries for MCP servers, APIs, SDKs
import type { MarketplaceEntry } from './types';

export const MARKETPLACE_ENTRIES: MarketplaceEntry[] = [
  // ─── Featured ────────────────────────────────────────────────────────
  {
    id: 'mcp-slack',
    name: 'Slack MCP',
    type: 'mcp',
    description: 'Send messages, read channels, manage reactions via Slack API',
    longDescription: 'Full Slack workspace integration. Post messages, search history, manage channels, add reactions, upload files — all from Jarvis.',
    icon: 'MessageSquare',
    category: 'mcp',
    installs: 12400,
    rating: 4.8,
    author: 'NewLeaf',
    version: '2.1.0',
    transport: 'sse',
    authTypes: ['oauth2'],
    homepage: 'https://slack.com',
    docs: 'https://api.slack.com/docs',
    configTemplate: { type: 'mcp', transport: 'sse', authType: 'oauth2', endpoint: 'https://slack-mcp.newleaf.financial/sse', category: 'mcp', tags: ['slack', 'messaging', 'collaboration'] },
  },
  {
    id: 'mcp-github',
    name: 'GitHub MCP',
    type: 'mcp',
    description: 'Manage repos, issues, PRs, and actions from Jarvis',
    longDescription: 'Full GitHub integration. Browse repos, create/manage issues and PRs, trigger workflows, search code — all from your command center.',
    icon: 'Github',
    category: 'mcp',
    installs: 18700,
    rating: 4.9,
    author: 'GitHub',
    version: '3.0.1',
    transport: 'sse',
    authTypes: ['oauth2', 'bearer'],
    homepage: 'https://github.com',
    docs: 'https://docs.github.com/en/rest',
    configTemplate: { type: 'mcp', transport: 'sse', authType: 'oauth2', endpoint: 'https://api.github.com', category: 'mcp', tags: ['github', 'git', 'devtools', 'ci-cd'] },
  },
  {
    id: 'mcp-linear',
    name: 'Linear MCP',
    type: 'mcp',
    description: 'Issue tracking, sprints, and project management',
    longDescription: 'Linear integration for agile project management. Create and manage issues, track sprints, view roadmaps, and run standups.',
    icon: 'ListTodo',
    category: 'mcp',
    installs: 8900,
    rating: 4.7,
    author: 'Linear',
    version: '1.5.2',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://linear.app',
    docs: 'https://developers.linear.app/docs',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'api_key', endpoint: 'https://api.linear.app/graphql', category: 'mcp', tags: ['linear', 'project-management', 'sprints'] },
  },

  // ─── MCP Servers ─────────────────────────────────────────────────────
  {
    id: 'mcp-base44',
    name: 'Base44 MCP',
    type: 'mcp',
    description: 'Query entities, invoke functions, manage your Base44 app',
    longDescription: 'Your NewLeaf backend at your fingertips. Query 90+ entities, invoke 200+ functions, manage customers, billing, and operations.',
    icon: 'Database',
    category: 'mcp',
    installs: 4500,
    rating: 4.6,
    author: 'NewLeaf',
    version: '1.0.0',
    transport: 'http',
    authTypes: ['api_key', 'bearer'],
    homepage: 'https://base44.com',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'api_key', endpoint: 'https://app.base44.com/api', category: 'mcp', tags: ['base44', 'newleaf', 'crm', 'backend'] },
  },
  {
    id: 'mcp-n8n',
    name: 'n8n MCP',
    type: 'mcp',
    description: 'Trigger and monitor n8n workflows from Jarvis',
    longDescription: 'Connect to your n8n instance. Trigger workflows, check execution status, and pipe data between Jarvis and your automation engine.',
    icon: 'Workflow',
    category: 'mcp',
    installs: 6200,
    rating: 4.5,
    author: 'n8n',
    version: '1.2.0',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://n8n.io',
    docs: 'https://docs.n8n.io/api',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'api_key', endpoint: 'https://n8n.newleaf.financial/api/v1', category: 'mcp', tags: ['n8n', 'automation', 'workflow'] },
  },
  {
    id: 'mcp-notion',
    name: 'Notion MCP',
    type: 'mcp',
    description: 'Read/write Notion pages, databases, and blocks',
    icon: 'FileText',
    category: 'mcp',
    installs: 15000,
    rating: 4.7,
    author: 'Notion',
    version: '2.0.0',
    transport: 'http',
    authTypes: ['oauth2'],
    homepage: 'https://notion.so',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'oauth2', endpoint: 'https://api.notion.com/v1', category: 'mcp', tags: ['notion', 'docs', 'knowledge-base'] },
  },
  {
    id: 'mcp-figma',
    name: 'Figma MCP',
    type: 'mcp',
    description: 'Access Figma designs, components, and styles',
    icon: 'Palette',
    category: 'mcp',
    installs: 9800,
    rating: 4.4,
    author: 'Figma',
    version: '1.8.0',
    transport: 'http',
    authTypes: ['oauth2', 'bearer'],
    homepage: 'https://figma.com',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'oauth2', endpoint: 'https://api.figma.com/v1', category: 'mcp', tags: ['figma', 'design', 'ui'] },
  },
  {
    id: 'mcp-sentry',
    name: 'Sentry MCP',
    type: 'mcp',
    description: 'Error tracking, stack traces, and performance monitoring',
    icon: 'Bug',
    category: 'mcp',
    installs: 7200,
    rating: 4.6,
    author: 'Sentry',
    version: '1.4.0',
    transport: 'http',
    authTypes: ['api_key', 'bearer'],
    homepage: 'https://sentry.io',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'api_key', endpoint: 'https://sentry.io/api/0', category: 'mcp', tags: ['sentry', 'monitoring', 'errors'] },
  },
  {
    id: 'mcp-langfuse',
    name: 'Langfuse MCP',
    type: 'mcp',
    description: 'LLM observability, traces, and cost tracking',
    icon: 'Eye',
    category: 'mcp',
    installs: 3400,
    rating: 4.3,
    author: 'Langfuse',
    version: '1.0.1',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://langfuse.com',
    configTemplate: { type: 'mcp', transport: 'http', authType: 'api_key', endpoint: 'https://cloud.langfuse.com/api/public', category: 'mcp', tags: ['langfuse', 'observability', 'llm'] },
  },

  // ─── APIs ────────────────────────────────────────────────────────────
  {
    id: 'api-nmi',
    name: 'NMI Payments',
    type: 'custom_api',
    description: 'Process payments, manage vaults, query transactions',
    icon: 'CreditCard',
    category: 'api',
    installs: 2100,
    rating: 4.5,
    author: 'NewLeaf',
    version: '1.0.0',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://nmi.com',
    configTemplate: { type: 'custom_api', transport: 'http', authType: 'api_key', endpoint: 'https://secure.networkmerchants.com/api/transact.php', category: 'api', tags: ['nmi', 'payments', 'billing'] },
  },
  {
    id: 'api-resend',
    name: 'Resend Email',
    type: 'custom_api',
    description: 'Send transactional emails with Resend API',
    icon: 'Mail',
    category: 'api',
    installs: 5600,
    rating: 4.8,
    author: 'Resend',
    version: '1.0.0',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://resend.com',
    configTemplate: { type: 'custom_api', transport: 'http', authType: 'api_key', endpoint: 'https://api.resend.com/emails', category: 'api', tags: ['resend', 'email', 'notifications'] },
  },
  {
    id: 'api-openai',
    name: 'OpenAI API',
    type: 'custom_api',
    description: 'GPT-4, embeddings, DALL-E, Whisper via OpenAI',
    icon: 'Brain',
    category: 'api',
    installs: 28000,
    rating: 4.9,
    author: 'OpenAI',
    version: '1.0.0',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://platform.openai.com',
    configTemplate: { type: 'custom_api', transport: 'http', authType: 'api_key', endpoint: 'https://api.openai.com/v1', category: 'api', tags: ['openai', 'ai', 'llm'] },
  },

  // ─── n8n ─────────────────────────────────────────────────────────────
  {
    id: 'n8n-billing-recon',
    name: 'Billing Reconciliation',
    type: 'n8n',
    description: 'Daily billing recon workflow — reconcile NMI transactions',
    icon: 'ArrowLeftRight',
    category: 'n8n',
    installs: 890,
    rating: 4.2,
    author: 'NewLeaf',
    version: '1.0.0',
    transport: 'http',
    authTypes: ['api_key', 'bearer'],
    configTemplate: { type: 'n8n', transport: 'http', authType: 'api_key', endpoint: 'https://n8n.newleaf.financial/webhook/billing-recon', category: 'n8n', tags: ['n8n', 'billing', 'automation', 'reconciliation'] },
  },
  {
    id: 'n8n-slack-digest',
    name: 'Slack Daily Digest',
    type: 'n8n',
    description: 'Daily operations digest posted to Slack',
    icon: 'Newspaper',
    category: 'n8n',
    installs: 670,
    rating: 4.1,
    author: 'NewLeaf',
    version: '1.0.0',
    transport: 'http',
    authTypes: ['api_key'],
    configTemplate: { type: 'n8n', transport: 'http', authType: 'api_key', endpoint: 'https://n8n.newleaf.financial/webhook/slack-digest', category: 'n8n', tags: ['n8n', 'slack', 'reporting'] },
  },

  // ─── SDKs ────────────────────────────────────────────────────────────
  {
    id: 'sdk-claude-agent',
    name: 'Claude Agent SDK',
    type: 'typescript_sdk',
    description: 'Build and manage Claude agents with the official SDK',
    icon: 'Bot',
    category: 'sdk',
    installs: 35000,
    rating: 4.9,
    author: 'Anthropic',
    version: '0.4.7',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    configTemplate: { type: 'typescript_sdk', transport: 'http', authType: 'api_key', endpoint: 'https://api.anthropic.com/v1', category: 'sdk', tags: ['claude', 'anthropic', 'ai-agent', 'sdk'] },
  },
  {
    id: 'sdk-vercel-ai',
    name: 'Vercel AI SDK',
    type: 'typescript_sdk',
    description: 'The AI SDK — unified provider interface for LLMs',
    icon: 'Code',
    category: 'sdk',
    installs: 42000,
    rating: 4.8,
    author: 'Vercel',
    version: '6.0',
    transport: 'http',
    authTypes: ['api_key'],
    homepage: 'https://sdk.vercel.ai',
    configTemplate: { type: 'typescript_sdk', transport: 'http', authType: 'api_key', endpoint: 'https://api.openai.com/v1', category: 'sdk', tags: ['vercel', 'ai-sdk', 'streaming'] },
  },
];
