import CanvasShell from "@/components/canvas/CanvasShell";
import ArtifactRenderer, { type ArtifactData } from "@/components/canvas/ArtifactRenderer";

const DEMO_MARKDOWN = `# Jarvis OS — Weekly Operations Report

> Generated: May 30, 2026 · Period: Week 22 · Status: **Healthy**

---

## 📊 Key Metrics

| Metric | Value | Change | Status |
| ------ | ----- | ------ | ------ |
| Active Customers | 1,247 | +12 | 🟢 |
| Recovery Rate | 94.3% | +2.1% | 🟢 |
| Avg Response Time | 1.8s | -0.3s | 🟢 |
| Billing Success | 98.7% | +0.4% | 🟢 |
| Pending Tickets | 23 | -5 | 🟡 |
| Agent Calls | 1,892 | +47 | 🟢 |

---

## 🧠 AI Pipeline Health

### DeepSeek V4 Pro
\`\`\`json
{
  "model": "deepseek-v4-pro",
  "avg_latency_ms": 1247,
  "success_rate": 0.998,
  "tokens_this_week": 4847219,
  "peak_tps": 84
}
\`\`\`

### Smart Retry Engine
\`\`\`
Total attempts:    4,231
Soft recoveries:   3,987 (94.2%)
Hard declines:       244 (5.8%)
Avg retry delay:   14.3 min
\`\`\`

---

## 🔐 NMI Gateway Status

- **Customer Vault**: 1,247 active profiles
- **DPAN Coverage**: 99.1% of vaulted cards
- **Day-0 CIT Anchors**: 100% compliant
- **source_transaction_id**: BANNED (enforced 2026-05-05)

---

## 🏗️ Infrastructure

| Service | Status | Uptime |
| ------- | ------ | ------ |
| mvp-builder (PM2) | 🟢 Running | 99.97% |
| claude-agent-api | 🟢 Running | 99.99% |
| jarvis-os-clean (Vercel) | 🟢 Ready | 100% |
| nginx tunnel | 🟢 Active | 99.95% |
| E2B Sandbox | 🟢 Available | 99.82% |

---

## ⚠️ Alerts

- **None critical** — all systems nominal

> *Report auto-generated by Jarvis OS Canvas Engine v1.0*
`;

const DEMO_ARTIFACT: ArtifactData = {
  type: "report",
  content: DEMO_MARKDOWN,
};

export default function DemoReportPage() {
  return (
    <CanvasShell slug="demo-report" title="Weekly Operations Report" status="complete">
      <ArtifactRenderer artifact={DEMO_ARTIFACT} />
    </CanvasShell>
  );
}
